model = "PrimeIntellect/Qwen3-0.6B-Reverse-Text-SFT"
max_steps = 100
batch_size = 32
rollouts_per_example = 32
oversampling_factor = 3.0
max_async_level = 3

[sampling]
max_tokens = 4096

[[env]]
id = "wambosec/injection-detector"
args = { dataset_name = "wambosec/prompt-injections" }

[buffer]
online_difficulty_filtering = true
easy_threshold = 0.8
hard_threshold = 0.2
easy_fraction = 0.1
hard_fraction = 0.6

[val]
num_examples = 32
rollouts_per_example = 4
interval = 5

[eval]
interval = 20
num_examples = 100
rollouts_per_example = 1
