model = "Qwen/Qwen3-4B-Instruct-2507"
max_steps = 100
batch_size = 4
rollouts_per_example = 4

[sampling]
max_tokens = 2048

[[env]]
id = "wambosec/injection-detector"
args = { generator_model = "qwen/qwen3-235b-a22b-instruct-2507" }
